apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config-server
    spec:
      containers:
      - image: dockerhub.secondstep.com/msa/config-server:latest
        name: config-server
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/config-server
          name: config-server-claim0
      restartPolicy: Always
      volumes:
      - name: config-server-claim0
        persistentVolumeClaim:
          claimName: config-server-claim0
status: {}
