apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: customer-service
  name: customer-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: customer-service
    spec:
      containers:
      - command:
        - /opt/bin/customer.sh
        image: dockerhub.secondstep.com/msa/customer-service:latest
        name: customer-service
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/customer-service
          name: customer-service-claim0
      restartPolicy: Always
      volumes:
      - name: customer-service-claim0
        persistentVolumeClaim:
          claimName: customer-service-claim0
status: {}
