apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: oauth-server
  name: oauth-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: oauth-server
    spec:
      containers:
      - command:
        - /opt/bin/oauth.sh
        image: dockerhub.secondstep.com/msa/oauth-server:latest
        name: oauth-server
        ports:
        - containerPort: 7000
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/oauth-server
          name: oauth-server-claim0
      restartPolicy: Always
      volumes:
      - name: oauth-server-claim0
        persistentVolumeClaim:
          claimName: oauth-server-claim0
status: {}
